services:
  backend:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PORT: ${DATABASE_PORT_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PROTOCOL: ${DATABASE_PROTOCOL}
      #DATABASE_HOST: ${DATABASE_HOST}
    ports:
      - ${TOMCAT_PORT_HOST}:${TOMCAT_PORT_CONTAINER}
    volumes:
      - ${PWD}/todoApp/wars:${CATALINA_HOME}/webapps
      - ${PWD}/services/tomcat/logs/:${CATALINA_HOME}/logs
  db:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT_HOST}:${DATABASE_PORT_CONTAINER}
    volumes:
      -  ${PWD}/services/database/:/docker-entrypoint-initdb.d